version: '3.7'
services:
  mongodb:
    image: mongo:latest
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
   image: ${DOCKER_REGISTRY-}api:${TAG:-latest}
   build:
     context: ./api
     dockerfile: Dockerfile
   depends_on:
     - mongodb
   ports:
     - 1000:1000

  app:
    image: ${DOCKER_REGISTRY-}app:${TAG:-latest}
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
volumes:
  mongodb_data_container: